Desktop: Rich Text Editor: Fix error observed while editing
While editng a note, the following error was observed in the console:
```
TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at resetLinkTooltips (useLinkTooltips.ts:9:38)
    at execOnChangeEvent (TinyMCE.tsx:1268:3)
    at Timeout._onTimeout (TinyMCE.tsx:1319:10)
    at listOnTimeout (node:internal/timers:605:17)
    at processTimers (node:internal/timers:541:7)
```

This commit adds guards to useCallbacks that can be called when `editor`
is defined but has no document.